openapi: 3.1.0
info:
  title: RaaSWebAPIv2
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/mapMeta/{id}':
    get:
      summary: get MapMeta
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/mapMeta.v2.json
      operationId: get-mapMeta
    post:
      summary: post new MapMeta
      tags: []
      responses: {}
      operationId: post-mapMeta
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: ../models/common/updateDateObject.json
                - $ref: ../models/mapParams.v2.json
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: map id
  '/mapMeta/{id}/params':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: map id
    post:
      summary: post map params
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/mapParams.v2.json
      operationId: post-mapMeta-id-params
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/mapParams.v2.json
    get:
      summary: get map params
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/mapParams.v2.json
      operationId: get-mapMeta-id-params
  '/map/{map_id}/pgm':
    parameters:
      - schema:
          type: string
        name: map_id
        in: path
        required: true
    get:
      summary: get pgm url
      tags: []
      responses: {}
      operationId: getPGMmapURL
    put:
      summary: ''
      operationId: putPGMmap
      responses:
        '200':
          description: OK
  '/map/{map_id}/cost':
    parameters:
      - schema:
          type: string
        name: map_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: getCostmapURL
    put:
      summary: ''
      operationId: putCostmap
      responses:
        '200':
          description: OK
components:
  schemas: {}
