openapi: 3.0.1
tags:
  - name: facility
  - name: robot
  - name: map
info:
  title: RaaSWebAPIv2
  version: '1.0'
  contact:
    name: onClouds
  description: rass APiv2
servers:
  - url: 'http://localhost:3000'
paths:
  '/maps/{map_id}':
    description: mapの取得
    get:
      summary: get MapMeta
      tags:
        - map
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/mapMeta.v2.json
      operationId: getMapMeta
      description: Idを指定してMapの取得
    post:
      summary: post new MapMeta
      tags:
        - map
      responses:
        '200':
          description: OK
      operationId: postMapMeta
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/mapMeta.v2.json
        description: ''
      description: Mapの登録
    parameters:
      - schema:
          type: string
        name: map_id
        in: path
        required: true
  '/maps/{map_id}/params':
    parameters:
      - schema:
          type: string
        name: map_id
        in: path
        required: true
    post:
      summary: post map params
      tags:
        - map
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/mapParams.v2.json
      operationId: postMapMetaIdParams
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/mapParams.v2.json
      description: 詳細説明なし
    get:
      summary: get map params
      tags:
        - map
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/mapParams.v2.json
      operationId: getMapMetaIdParams
      description: 詳細説明なし
  '/maps/{map_id}/pgm':
    parameters:
      - schema:
          type: string
        name: map_id
        in: path
        required: true
    get:
      summary: get pgm url
      tags:
        - map
      responses:
        '200':
          description: OK
      operationId: getPGMmapURL
      description: 詳細説明なし
    put:
      summary: ''
      operationId: putPGMmap
      responses:
        '200':
          description: OK
      tags:
        - map
      description: 詳細説明なし
  '/maps/{map_id}/cost':
    parameters:
      - schema:
          type: string
        name: map_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - map
      responses:
        '200':
          description: OK
      operationId: getCostmapURL
      description: 詳細説明なし
    put:
      summary: ''
      operationId: putCostmap
      responses:
        '200':
          description: OK
      description: 詳細説明なし
      tags:
        - map
  '/facilities/{facility_id}':
    parameters:
      - schema:
          type: string
        name: facility_id
        in: path
        required: true
    get:
      summary: get Facility
      tags:
        - facility
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/facility.json
      operationId: getFacilityByID
      description: 詳細説明なし
    post:
      summary: post Facility
      operationId: potFacilityByID
      responses:
        '200':
          description: OK
      tags:
        - facility
      description: 詳細説明なし
  /facilities:
    get:
      summary: Your GET endpoint
      tags:
        - facility
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagenate:
                    $ref: ../models/common/pagenateTemplate.v1.json
                  data:
                    type: array
                    items:
                      $ref: ../models/facility.json
      operationId: getFacilities
      description: 詳細説明なし
    parameters: []
  /maps:
    get:
      summary: Your GET endpoint
      tags:
        - map
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagenate:
                    $ref: ../models/common/pagenateTemplate.v1.json
                  data:
                    type: array
                    items:
                      $ref: ../models/mapMeta.v2.json
                required:
                  - pagenate
                  - data
      operationId: getMaps
      parameters:
        - schema:
            type: string
          in: query
          name: search
          description: 検索文字列
        - schema:
            type: number
          in: query
          name: page
          description: ページ数
        - schema:
            type: number
          in: query
          name: limit
          description: 表示数
      description: 詳細説明なし
    parameters: []
components:
  schemas: {}
  responses: {}
  parameters:
    map_id:
      name: map_id
      in: path
      required: true
      schema:
        type: string
