openapi: 3.1.0
info:
  title: RaaSWebAPIv2
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/maps/{map_id}':
    get:
      summary: get MapMeta
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/mapMeta.v2.json
              examples:
                example-1:
                  value:
                    id: '0000000000000054'
                    name: ToyotaStadiumv2
                    description: ToyotaStadium-res0.1
                    resolution: 0.1
                    origin:
                      x: -200
                      'y': -200
                    negate: false
                    occupied_thresh: 0.65
                    free_thresh: 0.196
                    size:
                      width: 4000
                      height: 4000
                    pgm_link: '{url}/maps/{map_id}/pgm'
                    costmap_link: '{url}/maps/{map_id}/cost'
                    yaw: 0
      operationId: get-mapMeta
    post:
      summary: post new MapMeta
      tags: []
      responses: {}
      operationId: post-mapMeta
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: ../models/common/updateDateObject.json
                - $ref: ../models/mapParams.v2.json
    parameters:
      - schema:
          type: string
        name: map_id
        in: path
        required: true
  '/maps/{map_id}/params':
    parameters:
      - schema:
          type: string
        name: map_id
        in: path
        required: true
    post:
      summary: post map params
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/mapParams.v2.json
      operationId: post-mapMeta-id-params
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/mapParams.v2.json
    get:
      summary: get map params
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/mapParams.v2.json
      operationId: get-mapMeta-id-params
  '/maps/{map_id}/pgm':
    parameters:
      - schema:
          type: string
        name: map_id
        in: path
        required: true
    get:
      summary: get pgm url
      tags: []
      responses: {}
      operationId: getPGMmapURL
    put:
      summary: ''
      operationId: putPGMmap
      responses:
        '200':
          description: OK
  '/maps/{map_id}/cost':
    parameters:
      - schema:
          type: string
        name: map_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: getCostmapURL
    put:
      summary: ''
      operationId: putCostmap
      responses:
        '200':
          description: OK
  '/facilities/{facility_id}':
    parameters:
      - schema:
          type: string
        name: facility_id
        in: path
        required: true
    get:
      summary: get Facility
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/facility.json
      operationId: getFacilityByID
    post:
      summary: post Facility
      operationId: potFacilityByID
      responses:
        '200':
          description: OK
  /facilities/:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ../models/common/pagenateTemplate.v1.json
                  - type: array
                    items:
                      $ref: ../models/facility.json
      operationId: getFacilities
  /maps/:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ../models/common/pagenateTemplate.v1.json
                  - type: array
                    items:
                      $ref: ../models/mapMeta.v2.json
      operationId: get-maps
      parameters:
        - schema:
            type: string
          in: query
          name: search
          description: 検索文字列
        - schema:
            type: number
          in: query
          name: page
          description: ページ数
        - schema:
            type: number
          in: query
          name: limit
          description: 表示数
components:
  schemas: {}
  responses: {}
  parameters:
    map_id:
      name: map_id
      in: path
      required: true
      schema:
        type: string
        example: '0000000000000013'
        minLength: 16
        maxLength: 16
